### ISSUE TITLE
Pinned Tweet for General Magic

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/gm-planning#109]
We want to have a pinned tweet that talks about what GM does. 

@anamarija09 started with the following, please leave comments on this doc: https://docs.google.com/document/d/1mAOqYNeoCWqeC3ejq2lRdHOUzEznZUY6uhqV7NqxIUg/edit

@divine-comedian @markoprljic

**Comment by markoprljic** [comment]
I made some suggestions, please review @ahmadabugosh

**Comment by markoprljic** [comment]
@anamarija09 Should also review and collect links and images for the tweet thread.

**Comment by anamarija09** [comment]
@markoprljic can you leave comments, I added your suggestions at the end:
https://docs.google.com/document/d/14uF8GNpDTFJj6GY7FWu1yak6EL59JYH9/edit?usp=sharing&ouid=113230950912230798952&rtpof=true&sd=true

**Comment by ahmadabugosh** [comment]
Thanks @markoprljic @anamarija09 I think the tweet thread is good to go (I cleaned up the last Marko section at the end, fixed a few small mistakes and made it fit in the character limit). Can you post it @anamarija09 ?  :)
