### ISSUE TITLE
Web3 Swag Shop Promotion

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#134]
### What?
Promote our Web3 Swag Shop to Impact DAOs and similar organizations and convert them into paying customers. 

### Why?
We want to deploy as many Swag Shops as possible. 

### Success metrics
- Lead Conversion Rate >10%
- Lead-to-Sale Conversion Rate >25%

### Next steps

- [x] Define the offer and possible options (with/without custom design, maintenance and store manager, revenue share model etc.)
- [x] Draft forum post template to introduce GM and the Swag Shop
- [x] Selection of Impact DAOs to contact
- [x] Review the content of existing landing page and adjust if needed
- [x] Tracking leads in Hubspot?
- [x] Ensure resources available to deploy new shops for customers
- [x] Ensure smooth deployment process, clarity on the timeline and any 3rd party dependencies

**Comment by markoprljic** [comment]
Speaking with Griff the other day he recommended that we partner with ENS DAO Comms team and align the promotions and communication around the Swag shops. They will be promoting the ENS Swag shop and at the same time we want to promote our Swag Shop product. 
Since we already have a great deal with them it would be wise to partner on the Comms side as well.

**Comment by markoprljic** [comment]
@tomislavmamic FYI

**Comment by tomislavmamic** [comment]
I was talking about it with Spencer from ENS DAO and my proposal to him was that we prepare or draft for them twitter thread about the shop. We would also prepare our own twitter thread. Also, we will prepare and post in ENS Forum a post announcing the swag shop. He didn't mention comms team, and I forgot to ask. I will message them to see if we can have a call with them.

**Comment by ahmadabugosh** [comment]
Thanks @tomislavmamic ! Let me know what they say. Also, can you see if we can schedule something with them next week?

**Comment by tomislavmamic** [comment]
They said we need to first complete the shop and then they will share it with TNL team. Also, they don't think it will need much promotion effort. Especially if Nick and other OGs share. They believe we will sell more than 2000 hats initially.

**Comment by ahmadabugosh** [comment]
Thanks @tomislavmamic but I think we still want to have a meeting with them to build relations with them and plan out how we can market together (also on an ongoing basis). Can you introduce @anamarija09 and I to their team?

**Comment by markoprljic** [comment]
@Zeptimus

**Comment by Zeptimus** [comment]
Marked proposal template as done: https://docs.google.com/presentation/d/1To4owUxi_vbUui6k3wGORTU2PFsESo4DTu6wU3Iy4e4/edit#slide=id.p1

(praise ahmad for that)

**Comment by Zeptimus** [comment]
This we have the 3 tiers https://docs.google.com/document/d/1StuQyUNzApZfzAE-9coPvksfIrDt7s5BCDfsolR3BNY/edit#

@ahmadabugosh   is working on making those a presentation it's good to have both formats one to present and the other to post on forums
