### ISSUE TITLE
Product images are stretched

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#136]

**Comment by markoprljic** [comment]
![Screenshot 2022-10-03 at 12.50.54.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/cc0b2d2f-56ba-4bda-89d0-c56bd00a42b6)
All images loaded on the homepage look stretched. I was checking on Category listing and they seem to be fine there.

**Comment by kkatusic** [comment]
@markoprljic can you open website in incognito mode and see is there any changes?

**Comment by markoprljic** [comment]
Still look squeezed.

**Comment by kkatusic** [comment]
Open browser, open that link, right click, in dropdown menu choose "Inspect element", it will open developer console, than choose Network tab, check "Disable cache" and than refresh page and let me know ;)

**Comment by markoprljic** [comment]
I did, I tried different browser as well. Still the same.
Maybe @rodricastillo9013 @ahmadabugosh try it out as well and let us know?

go to https://swag.generalmagic.io/ and check if product images looked stretched on the homepage, make sure to go to page 2 and 3.

**Comment by ahmadabugosh** [comment]
Yes still looked stretched to me. Are we using a CDN or something that could be caching it?

**Comment by rodricastillo9013** [comment]
I see it well! I don't see it stretched! @kkatusic @markoprljic

**Comment by kkatusic** [comment]
> I see it well! I don't see it stretched! @kkatusic @markoprljic

I fixed it.
