### ISSUE TITLE
Create proposals to other DAOs

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#138]
### Goal
Increase GM presence and brand/services awareness in the Impact DAO and Public Good space.

### Objective 
Finding needs that DAO's have and offering our services and products to them. Find other ecosystem funding opportunities for builders (grants, programs, bounties etc.)
Write 10 formal proposals to different DAO's offering our products and/or services.

Creating proposals targeting specific DAOs and their needs with the tools and products we already have or we could build for them. 
Example: https://forum.gnosis.io/t/gip-67-should-gnosisdao-fund-gnosis-chain-ecosystem-analysis-and-dashboard/6000

### Outcome 
3 high paid contracts in Q4 2022.

**Comment by markoprljic** [comment]
Got it. You are referring to our services, right? Not the products like Swag Shop and Praise? @Zeptimus

**Comment by markoprljic** [comment]
Move fast and break things. We're a startup! 😁

**Comment by markoprljic** [comment]
@Zeptimus Your findings and possible communication approach might also reflect in the Brochure we're about to create https://github.com/GeneralMagicio/gm-planning/issues/39 Please document your findings and provide any relevant info to @rodricastillo9013

**Comment by Zeptimus** [comment]
My findings are here let me know if that's what you had in mind @markoprljic  or i should build something different.

https://docs.google.com/spreadsheets/d/1Ps6UxPLlqIdxp8vBJjpOBjhtGYFgKNgCGWrED8PY2to/edit#gid=1573214684

**Comment by Zeptimus** [comment]
We are moving this to Hubspot for better team coordination this doc  will probably get less and less attention 

https://docs.google.com/spreadsheets/d/1Ps6UxPLlqIdxp8vBJjpOBjhtGYFgKNgCGWrED8PY2to/edit#gid=1573214684
