### ISSUE TITLE
Submit Optimism Grant

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#152]

**Comment by Zeptimus** [comment]
done my post is hide 
![imagen](https://user-images.githubusercontent.com/74430951/198701521-982dcdc0-88b4-4153-8729-87a1e0fd61d5.png)
Thats what i posted
https://docs.google.com/document/d/1S8FfImez2JIhINXu_TqaH8kux7OFry37h-zxPTnIHO8/edit#

And created this thread for getting feedback https://discord.com/channels/667044843901681675/1034442734502674463

Will close the issue when the post is public

**Comment by Zeptimus** [comment]
Done :D https://gov.optimism.io/t/draft-gf-phase-1-proposal-cycle-8-optimism-merch-shop/3828
