### ISSUE TITLE
Create Offer Letter template for GM

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/gm-planning#25]

**Comment by ahmadabugosh** [comment]
Hey I made a draft of this offer letter, let me know what you think @freshelle (once you're back from vacation of course!) https://docs.google.com/document/d/1OX3ZeAE6BQXDonN5L7pMSENOwurAxPPaZveLbI-y6T4/edit?usp=sharing

**Comment by freshelle** [comment]
This looks great, Ahmad! Left some comments in the doc

**Comment by markoprljic** [comment]
Is this done? Can we close it?

**Comment by ahmadabugosh** [comment]
@markoprljic yes this is done, closing this now
