### ISSUE TITLE
Hatch Config Dashboard needs design to get started

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/gm-planning#28]
Here is the old Dashboard:
http://params.tecommons.org/hatch

We need to make a white label-able new version that is as sexy as: https://config.tecommons.org

**Comment by markoprljic** [comment]
Need PM, Designer and Devs together with Vitor.

Would be good to start in August and deliver mid October.

**Comment by VMLVaske** [comment]
The Hatch Dashboard has had it's initial Call with Tamara. Team Roster is set (Vitor, Pedro, Tosin, Marko, Valerie).

**Comment by markoprljic** [comment]
Ok, so I guess this issue can be closed and we could create a new repo specially for the Hatch to PM the whole project? 
We also need to write up all the requirements and necessary steps needed to complete each phase of the project.
