### ISSUE TITLE
Praise Bot for GM

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#32]
Integrate Praise bot to GM discord server.

**Comment by markoprljic** [comment]
@Vyvy-vi Where is the Praise data saved? Can we save that in our Google Drive folder? 
Is there anything else we should be aware of when setting this up?

**Comment by Vyvy-vi** [comment]
closing this one (clone of #53)

If we're implementing the new praise system, the data would be stored on the DigitalOcean droplet we would be using.
