### ISSUE TITLE
Panvala Website redesign

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#4]

**Comment by markoprljic** [comment]
@rodricastillo9013 Rachel and Margaret left some comments in Figma, please review and let me know if you have any questions.
Do you think we can make all revisions and finalize it this week?

**Comment by rodricastillo9013** [comment]
ok perfect, yes I'll work on it. @markoprljic

**Comment by markoprljic** [comment]
This one is closed @rodricastillo9013 We started webflow integration, design part is done. Hoooray! Great job!

**Comment by rodricastillo9013** [comment]
ok!! nice! thanks marko! :)
