### ISSUE TITLE
Set up a Swag Shop for GM

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#42]
We would like to set up a Swag Shop for GM. 
Ideally we would want it to be hosted on our server and domain, and have a Printful account.
For the MVP we could possibly set up GM shop under existing CS and Giveth shops, and use their Printful? 

Go live soonest possible and when we have artwork ready.

**Comment by kristoferlund** [comment]
I'd like to pass this ball to RB.

**Comment by markoprljic** [comment]
Do we have him here? How should he be informed?

**Comment by kristoferlund** [comment]
> Do we have him here? How should he be informed?

I don't seem to have permissions to invite him. 

salupado.rb@gmail.com

**Comment by rbsal97** [comment]
Hi Team, will be working on this.
