### ISSUE TITLE
Design artwork for Swag shop and upload to Printful

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#43]
We need swag designs for our shop.

- Tshirt
- Hoodie
- Hat
- Mug
- Stickers

We will use Printful shop and they have print specifications already https://www.printful.com/blog/everything-you-need-to-know-to-prepare-the-perfect-printfile/

Once designs are created and approved we need to upload them to Printful:
- choose mockups, materials and price
- set up product titles and other details needed

**Comment by markoprljic** [comment]
I'll add Lulu to this task once she joins our repo.

**Comment by markoprljic** [comment]
Tagging you for awareness @luluavalloni

**Comment by rodricastillo9013** [comment]
hi team! perfect. we'll move on with this :)

**Comment by luluavalloni** [comment]
Working on it!
