### ISSUE TITLE
Copywriting for GM Website

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#45]
We need to write the copy for our website. Landing page should explain who we are and what we do. 
We will probably need some other content for remaining pages like About us, Contact etc. 

Current draft https://giveth.notion.site/General-Magic-Website-Content-3d2f89657b754a3aa4f10c7a8ddfc45e

Inspiration websites, some communicate really well https://giveth.notion.site/Website-inspiration-e01e557ca4294256ba0186e1a877f6d1

Service DAOs landscape to look at https://twitter.com/Gems_Chill/status/1521062792484192256?t=Ofc3HRHfkbUe0WqKm41NEg&s=19

**Comment by zzaaiinnk** [comment]
Logged in, Marko. Will work on this tomorrow!

**Comment by markoprljic** [comment]
> Logged in, Marko. Will work on this tomorrow!

Nice! Thanks :)

**Comment by zzaaiinnk** [comment]
[https://app.zenhub.com/files/465670090/4b29b94a-d324-491c-b9ff-91e7028b8537/download](https://app.zenhub.com/files/465670090/4b29b94a-d324-491c-b9ff-91e7028b8537/download)

**Comment by zzaaiinnk** [comment]
Please read through @markoprljic and let us know if we are close to your expectation. Still trying more to understand the Target Group and happy to refine it further. Looking forward.

**Comment by markoprljic** [comment]
Thanks!

@divine-comedian @ahmadabugosh Want to review this as well?

**Comment by ahmadabugosh** [comment]
Thanks @zzaaiinnk ! Would you be able to share it as a Google doc and allow "Anyone to comment"? That would make it easier for us to give feedback

**Comment by zzaaiinnk** [comment]
Yes, I can do that next @markoprljic - but I will need the scope, Target Group, and keywords to write from scratch. I was under the impression that you want the existing content to be refined. Please let me know if that's the other way. Thanks!

**Comment by zzaaiinnk** [comment]
> Thanks @zzaaiinnk ! Would you be able to share it as a Google doc and allow "Anyone to comment"? That would make it easier for us to give feedback

Here is the Gdocs link @ahmadabugosh @markoprljic - feel free to comment and provide feedback
