### ISSUE TITLE
Creating $TRUST concept to be associated to TS Swag Shop

### ISSUE THREAD

**Issue by rbsal97** [GeneralMagicio/gm-planning#48]
We need ideas on how to introduce & associate $TRUST concept to our Trusted Seed Swag Shop.

Areas for discussion:

1. Concept of $TRUST
2. Ideas on how to build narrative around $TRUST (Discussion or concept flow).
3. Actual narratives or points of discussion we can work on to associate on TS Swag Shop Page.

After we get to finalize the concept and summarize all the ideas, we can then create effective marketing for $TRUST on the Swag Shop.

**Comment by rbsal97** [comment]
Hi @mafer-cordovas, for your reference! Thanks for helping us out!

**Comment by mafer-cordovas** [comment]
Here are the requested concepts:

1. Concept of $TRUST

$TRUST is a non-transferrable reputation token representing the “skin in the game” that value-driven members of the blockchain community have put towards advancing Commons Stack’s mission.

Anyone holding $TRUST is a member of our Trusted Seed, a highly curated list of reputable & experienced community members who are aligned with our mission of creating sustainable funding for public goods using token engineering and commons management best practices.

2. $TRUST as reputation, a cool token to have, public good promoter/philanthropist, seeding commons, valuable network, building for good, attractive community.


The 1st concept is as requested. 2nd point are some ideas of narrative.
@rbsal97 @rodricastillo9013

**Comment by rodricastillo9013** [comment]
Hello, thanks for your contribution!
I have some questions.

- Should we make an identity for $TRUST to then add it to the TS Swagshop?

- In case of developing a proper identity for this token, should we relate it to the TS design line?
@mafer-cordovas @rbsal97

**Comment by rbsal97** [comment]
Hi Rodri!
I think we should make an identity for it and also relate it to the TS Design. But I think what marko also suggest is that we create a brief introduction on the $TRUST concept within our TS Swag Shop page?

**Comment by rodricastillo9013** [comment]
we have coordinated with @rbsal97 

- I will work on a $trust section where we will explain the concept and add the information that @mafer-cordovas  gave us
- From there we can work polishing the content collaboratively in figma.
- Once defined, a developer will implement it in the TS Swag Shop.

FYI @markoprljic

**Comment by rodricastillo9013** [comment]
we can start working on this page, could you help me with the definition of the content and I can finish styling the design 

https://www.figma.com/file/X9XOjDIS6U8AEssNxx3SED/Trusted-Seed-Dashboard?node-id=1558%3A37 @rbsal97 @mafer-cordovas

**Comment by rodricastillo9013** [comment]
some feedback for this? @mafer-cordovas @rbsal97

**Comment by mafer-cordovas** [comment]
@rodricastillo9013 I have requested editing powers on figma

**Comment by rbsal97** [comment]
Pretty good for me! For the 3 blocks below I suggest: Uses, Importance, History.

**Comment by rodricastillo9013** [comment]
nice! Done @mafer-cordovas

**Comment by mafer-cordovas** [comment]
I have added all the content needed on the $trust page. I also added a comment on Figma to change the '$' on the background @rodricastillo9013 
![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/925ce527-19f1-4775-8a0c-e405b1fbcd04)

I also put titles to the ones saying 'ICON' just so if you do add icons, that's the topic 
![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/b2618201-c8f7-4f57-bc13-b8020430d251)

I will review this phrase with Griff
![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/fccfc0c4-a404-470b-bc01-b260a2f2e911)

**Comment by rbsal97** [comment]
Hi @rodricastillo9013 and @mafer-cordovas, can we close this one? Thanks for the awesome work!

**Comment by mafer-cordovas** [comment]
Close it with awesomeness!
