### ISSUE TITLE
clrFund EF Theme Redesign

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#50]
From Auryn:

So the current need is really just to tidy up the designs of the new version of the app.
The ethereum.org crew did a really nice job updating the app, but we would like to simplify the CSS so that it's really easy for others to come in and change few hex colours and images to rebrand clrfund for their project.

https://clr.fund/#/

Figma UI https://www.figma.com/file/4Y1QtjKO9iUuKIJbDhtDg1/clr.fund-EF-Theme-Redesign?node-id=589%3A3449

**Comment by rbsal97** [comment]
**_Deliverable_**

Figma File: https://www.figma.com/file/4Y1QtjKO9iUuKIJbDhtDg1/clr.fund-EF-Theme-Redesign?node-id=10%3A0

@markoprljic @peteredebs

**Comment by markoprljic** [comment]
I'm not seeing Components and Sections being done.
We should also update the illustration page when Lulu is done.

**Comment by peteredebs** [comment]
@markoprljic on it!

**Comment by rbsal97** [comment]
Additional Components Checklist:

- About page (subpages are all the same)
- Cart with several states and some modals
- Projects with several states and some modals
- Join (this seems a bigger one)
- Projects (single page, rounds, round information)
- Transaction success, fail 
- Verify
- Wallet 

cc: @peteredebs

**Comment by peteredebs** [comment]
Ready for review @markoprljic

**Comment by markoprljic** [comment]
Left some comments in Figma @peteredebs
