### ISSUE TITLE
ABC Advanced Page (TEC)

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#51]

**Comment by tamarandom** [comment]
This issue can probably replace #23 now. 

Zeptimus is in the process of finalizing the Creative Brief. It should be finished today-ish. 
https://docs.google.com/document/d/12rYtT9vHnBF0i84qz-MAORfMQ4Q5rVZFoIALNoGrY7U/edit#

**Comment by Zeptimus** [comment]
Together with the Creative Brief we also created wireframes [here.](https://miro.com/app/board/uXjVO7-FzCI=/) 

We need a designer to start working on those, there are some concerns regarding the complexity of module 1 that probably we need the eyes of someone that is not deeply involved to make sure it's easy to understand for new users, I'm happy to explain how it technically works and do QA of the designs.

**Comment by markoprljic** [comment]
@rodricastillo9013 @peteredebs

**Comment by rodricastillo9013** [comment]
hello everyone, it will be a pleasure to help with this project, we will work together with our colleague @jesicadg , we will start with this next week. 

We will review all the information and notify you of any questions we may have.

@tamarandom @Zeptimus @markoprljic

**Comment by peteredebs** [comment]
@rodricastillo9013 Updates on this? Can I be added?

**Comment by markoprljic** [comment]
Yeah, I think you could work on this as well. We'll coordinate.

**Comment by Zeptimus** [comment]
Hey peter nice to meet you! Me rodri and tam will have a first meeting feel free to join here: https://meet.jit.si/UndergroundTuesdaysMoveHighly
Will update here what we talk there.

**Comment by Zeptimus** [comment]
We had a meeting with Rodri

1- Wireframes are clear.

2- We will be working async on the figma file https://www.figma.com/file/b6kx4mkaHxzq4TPzaI1eRY/TEC-Dapps?node-id=2663%3A12872

3- We will use TEC branding but keep the template for make it easily replicable for other commons
Rodri will be working this week on a realistic version  (full freedom of designs) of the wireframes and we will have a review on it next friday and present it for QA to the rest of the team (Monday~Tuesday).

4- Will have 2 different designs 1 that include the whole project and 1 with heather modul 1 and 3 (and the empty space covered with work in progress/TEC) for a quicker soft launch

5- Getting designs finish will take 2-3 weeks

**Comment by markoprljic** [comment]
@zeptimus @rodricastillo9013 Is this completed? Can we close this Issue and Epic?

**Comment by Zeptimus** [comment]
Designs are complete unless Mateo says that he needs some edits meanwhile deploying it, aiming to get this product done late September development started a week ago.

**Comment by markoprljic** [comment]
Ok thanks. Can you confirm with Mateo? I'm looking to close the issue since it was created for design part. Unless you want to keep it open for your overview.

**Comment by Zeptimus** [comment]
we can close it, ive created a new one on the TEC repo for keep tracking of it. Praise rodri for the amazing desings!

**Comment by markoprljic** [comment]
Thanks!
