### ISSUE TITLE
Praise System for GM

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#53]

**Comment by kristoferlund** [comment]
We discussed this yesterday and concluded to wait with GM praise until there is someone that can take on the role as "Praise-facilitator". Someone need to open and close rounds, lead the quantifications etc. Or maybe @Vyvy-vi you are that person? :) Mitch has enough of that over at TEC.

**Comment by markoprljic** [comment]
Do we have any instructions on how this is done, step by step? We could assign someone for this admin task if it doesn't require great skills and Web3 knowledge that can't be learned fast.

**Comment by kristoferlund** [comment]
Best way is to join the TEC for a praise round or two to learn the process.

**Comment by markoprljic** [comment]
There's no way someone could write this in a doc?

**Comment by markoprljic** [comment]
No easy task 🙂

**Comment by kristoferlund** [comment]
> No easy task 🙂

I do think the forum posts are quite easy to follow. And like I said, whoever takes on the task, we will support that person - answer any questions etc.

**Comment by Vyvy-vi** [comment]
I would be willing to set up praise and  facilitate praise for a while

**Comment by markoprljic** [comment]
Amazing! Thanks @Vyvy-vi 
We should however, teach someone who's willing to facilitate praise quant later. I'm just thinking of best way to have a doc that can serve as tutorial for that.

**Comment by Vyvy-vi** [comment]
> Amazing! Thanks @Vyvy-vi We should however, teach someone who's willing to facilitate praise quant later. I'm just thinking of best way to have a doc that can serve as tutorial for that.

Yes, I think we should make a Praise Gitbook ASAP(at least before we distribute praise to Gnosis and others)

**Comment by kristoferlund** [comment]
> Yes, I think we should make a Praise Gitbook or docs ASAP(at least before we distribute praise to Gnosis and others)

That is high up on my todolist. During the process of helping Gnosis and Giveth to get set up we will be filling that handbook with material.

**Comment by kristoferlund** [comment]
Praise landing page and docs site is up. Now only thing missing is the content.. 😄 

And .. nicer design for the landing page and the app, nudge nudge @markoprljic, whenever someone in the design team has capacity. 

https://givepraise.xyz

**Comment by markoprljic** [comment]
Nice @kristoferlund :)

So what I'm hearing is: 
- Landing page design of https://givepraise.xyz/ using the existing content and what brand? CS?
- UI design of the Praise App, which is where?

**Comment by kristoferlund** [comment]
The TEC praise instance runs at https://praise.tecommons.org. 

I discussed the design issues with Tam earlier today. I think we concluded that CS don't have the budget to do any Praise design work just now. We'll continue that conversation on Monday. I'll follow up after that somewhere better than this thread.

**Comment by markoprljic** [comment]
Ok, thanks for the update @kristoferlund
