### ISSUE TITLE
clrFund Pool Party Illustration

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#57]
What would the pool party on the other side of the doorway/archway in the hero image of Ethereum.org look like?

Attached is the original moodboard created by another artist. 
Ethereum.org and poolsuit/vacation are good additions to the mood board.

https://ethereum.org/en/assets/
https://poolsuite.net/
https://www.vacation.inc/

![clr_moodboard_01.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/3d2877df-3c68-4cbe-8d05-9444aef148e5)

The illustration will be used in the header of the Homepage and some elements of the illustration might be used across the site, as small visual elements maybe in footer or elsewhere. 

This is the Figma for the new UI (work in progress) https://www.figma.com/file/4Y1QtjKO9iUuKIJbDhtDg1/clr.fund-EF-Theme-Redesign?node-id=10%3A0

**Comment by markoprljic** [comment]
![90F367CF-29E1-4B3D-955F-A4E0668CFF6F.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/9d48699d-f2ed-4802-a0a0-766f18275ca3)

**Comment by markoprljic** [comment]
![POOL_HEADER_GM_02.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/5179515a-c9d9-4913-901a-17b3c38a2c39)

**Comment by rbsal97** [comment]
Notes from Auryn:

The original prompt was something along the lines of "what would the pool party on the other side of the archway in the ethereum.org hero image look like" ?

The keywords I'd use to describe the vibe we want are: lunar punk, light-hearted, and diverse.

What we really need is just some general purpose artwork that can be re-used in a bunch of different contexts. The artwork that is on the app now is a good example of what we'd ultimately want to replace. (even though it's super cool, it's just not clr.fund)

@luluavalloni

**Comment by rbsal97** [comment]
**_Deliverable_**

Google Drive Link: https://drive.google.com/drive/folders/1lzA8N1SRi6J5N4xAneKzKKcCRVS0umR3?usp=sharing

**Comment by markoprljic** [comment]
Wow, love it!

**Comment by rbsal97** [comment]
I will be closing this one. Thanks! @luluavalloni 



![Image](https://user-images.githubusercontent.com/98407510/181266845-c8ed4c29-8347-46a6-b2d0-8f93ae3c200b.png)
