### ISSUE TITLE
clrFund - Define the design scope and requirements

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#58]
1. Set up a call with Auryn (reach out on discord channel)
2. Define the design scope and requirements
3. Submit Requirements document to this issue
4. Create a plan, milestones and deliverables

**Comment by rbsal97** [comment]
Project Deliverables:
1. A new color system for light and dark mode.
2. New Illustrations for Clr Fund.
3. Designs with the new color system implemented.

Estimate Timeline:
- 2 weeks.
@peteredebs

**Comment by peteredebs** [comment]
@rbsal97 This is Acknowledged.
