### ISSUE TITLE
ABC Graphics for the next article

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/gm-planning#6]
https://docs.google.com/document/d/1zSbu7WDYzCnNdpJA27gO4orLGUSqj0GxE-XZhasieP0/edit

Futuristic Vending Machine needs graphics

**Comment by rodricastillo9013** [comment]
hi!, we must generate graphics for this post, we continue with the aesthetics that we used for the previous post that we worked on? @GriffGreen

**Comment by markoprljic** [comment]
@rodricastillo9013 Status update?

**Comment by rodricastillo9013** [comment]
I didn't get an answer from Griff, we have a machine design for another article, I can apply it here, no problem. I will read the article again today and apply the designs that I think are necessary, and I will notify you so that you can send me feedback.

@markoprljic @GriffGreen

**Comment by markoprljic** [comment]
Consider @jesicadg if needed.

**Comment by markoprljic** [comment]
Any updates on this @rodricastillo9013 ?

**Comment by rodricastillo9013** [comment]
I wanted to try to work with jes, but I'll ask him if he can help, otherwise I'll finish it myself this week to close this. @markoprljic
