### ISSUE TITLE
Discord bot to fetch issues rom Github

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#68]
Where does someone see open tasks to work on when they land on Discord? 
Might be good to create a channel to feed new issues from github.

**Comment by Vyvy-vi** [comment]
Which repos do we need to track? Only `gm-planning`, or all the repos in the org?

**Comment by markoprljic** [comment]
Might be good to have only gm-planning because that's where all things start. However, this needs a bit more thought on:
- what issues do we want to show
- do we want to add labels o fetch only issues labeled as "Good first issue" open to contributors
- do we want to fetch based on epics / working groups (i.e. design, marketing, hr, development)

Maybe this one is lower priority until we decide on how this makes things easier for us, if it does at all.

**Comment by Vyvy-vi** [comment]
for now, all notifs from gm-planning get forwarded to discord

**Comment by markoprljic** [comment]
Great! Should we close this issue? I'm ok with that.
