### ISSUE TITLE
Create a list of projects that GM has worked on

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#72]
We need a list of projects that GM has worked on to show on our website under Projects page. 

Each project should have:

- Title
- Short description
- Services (design, dev, pm etc.) and Tech stack used (ask devs)
- People who worked on this project (GM members + any outside collaborators)
- Client name / Org we partnered with
- Logo or Screenshots of the project (ask Designers)

**Comment by markoprljic** [comment]
@rbsal97 Can you make this happen this week? You can get details of each project on their websites, forums, docs etc. and/or ask people who worked on these projects where to get basic info about it.

**Comment by markoprljic** [comment]
Projects I'm aware of:

- Giveth 
- Praise System (Commons Stack)
- Commons Simulator (Commons Stack)
- Trusted Seed Dashboard + Branding (Commons Stack)
- TEC website (TEC)
- TEC Hatch Dashboard (https://hatch.tecommons.org/)
- TEC Commons Upgrade (https://config.tecommons.org/)
- Swag Shop (Tally, Giveth, GM)
- BrightID CV parameters settings (https://forum.brightid.org/t/revisiting-the-brightdao-parameters-with-general-magic-support/355)

**Comment by rbsal97** [comment]
Hi Marko! Noted on this. FOr the documentation. Where will we keep all of this? @markoprljic

**Comment by markoprljic** [comment]
We can do it here https://www.notion.so/giveth/Projects-4ba94e9b410f44c6aa99722f764bc6f2
