### ISSUE TITLE
Create artwork for tshirts based on text quotes

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#73]
Quotes: 

A little magic can take you a long way.

There is magic, but you have to be the magician. 

If you are a magician then you can always do a lot more magic than you think you can.

Think like a magician, present like a magician and perform like a magician.

You have to make the magic happen.

Magic lies in challenging what seems impossible.

Magic is believing in yourself, if you can do that, you can make anything happen.

**Comment by ahmadabugosh** [comment]
Small typo,  it should be "Think like a magician, present like a magician and perform like a magician" (it was missing the "a")

**Comment by markoprljic** [comment]
Thanks @ahmadabugosh :)

**Comment by markoprljic** [comment]
Hey @luluavalloni sorry about this, but I have forgotten how these look like :)
Do you mind uploading screens here please? And also let me know if you uploaded them to our shared drive folder. Thanks!

**Comment by luluavalloni** [comment]
SWAG GM QUOTES 01.png
<https://drive.google.com/file/d/19cM4cCkEqJDLz5JFieK8KXlYX7U0qeOV/view?usp=drive_web>
 SWAG GM QUOTES 02.png
<https://drive.google.com/file/d/1ZLH3rBTG39uiNlR3ilNCJdU4DH8yoBCA/view?usp=drive_web>
 SWAG GM QUOTES 03.png
<https://drive.google.com/file/d/1Tk8ZXWSdneZFmgHeMQ3zM_yiFmrLX9Q5/view?usp=drive_web>
 SWAG GM QUOTES 04.png
<https://drive.google.com/file/d/1-XWdUhnV9NcXVrGiVyVLTDmlid0EgcA8/view?usp=drive_web>
 SWAG GM QUOTES 05.png
<https://drive.google.com/file/d/1IPZKyMlKJfLZF0Kr0l5X5tadhYJ_fQnn/view?usp=drive_web>
 SWAG GM QUOTES 06.png
<https://drive.google.com/file/d/1P8HfNx5wQvXgTpGr74EU35wm28XmYMIP/view?usp=drive_web>
 SWAG GM QUOTES 07.png
<https://drive.google.com/file/d/1y8j8JzKLwMRI0VSn0Kl5MatNUtGjvjq1/view?usp=drive_web>
sorry the delay, there you go!

Em seg., 5 de set. de 2022 às 09:53, Marko ***@***.***>
escreveu:

**Comment by luluavalloni** [comment]
They should be, but I'm finishing the last illustrations I have to do and
I'm gonna reupload everything I have on the drive so nothing is missing :D

Em sex., 9 de set. de 2022 às 08:45, Marko ***@***.***>
escreveu:

> Are these in our GM drive folder? Seems I don't have access to the ones you
> shared.
>
