### ISSUE TITLE
Create Partnership agreement and terms with Wesley (Tokenlog)

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#81]
- Apply for grants to get money, (but it will be free to use by others) 
- Long term partnership with Wesley
- Offer it as a product that we can deploy at cost
- We can deploy and charge, we split 80/20, and vice versa
- If any funds raised in the future we split the money 50/50
- Similar approach to CS
- Other ideas?

**Comment by markoprljic** [comment]
@ahmadabugosh Maybe we can wrap this up with Wesley with a simple format agreement / terms and close this Epic?

**Comment by ahmadabugosh** [comment]
@markoprljic Following up our discussion earlier, I belive we can close this (until we figure out how / if we want to monetize it)
