### ISSUE TITLE
Install Google Analytics on GM Website

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/gm-planning#97]

**Comment by kkatusic** [comment]
@markoprljic who can provide GA code?

**Comment by markoprljic** [comment]
MoeShehab or Ahmad.

**Comment by ahmadabugosh** [comment]
Hey @kkatusic , I recommend to use Google Tag Manager instead. That way we can easily add any future tags there (including GA, Google ads etc). 

Can you please include the following:

**In the <head>**

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WLQQCZP');</script>
<!-- End Google Tag Manager -->
```

**In the <body>**

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WLQQCZP"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by kkatusic** [comment]
Hi @ahmadabugosh , thx.

I think @luizakp will implement it, I don't work on this project, I thought this was for GM Swag Shop :)

**Comment by ahmadabugosh** [comment]
@kkatusic no worries! Actually, you can add the same code on the swag shop as well (it would make it easier for us to track if we use the same pixel).

**Comment by kkatusic** [comment]
@ahmadabugosh I added it to Swag Shop, you can check it ;)
